{
 "title": "Monitoring",
 "tags": [
  "prometheus",
  "http",
  "sqlite",
  "memory"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests Increase (Last 1 Minute)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Heap Memory Used (Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 14, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "heap_alloc" }
   ]
  },
  {
   "title": "Memory Alloc vs Free Count",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 14, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total[1m])",
     "legendFormat": "Mallocs"
    },
    {
     "expr": "rate(go_memstats_frees_total[1m])",
     "legendFormat": "Frees"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Targets",
   "type": "stat",
   "gridPos": { "x": 12, "y": 22, "w": 12, "h": 4 },
   "targets": [
    { "expr": "count(up == 1)", "legendFormat": "Up" }
   ]
  },
  {
   "title": "Users Count",
   "type": "stat",
   "gridPos": { "x": 0, "y": 32, "w": 8, "h": 4 },
   "targets": [
    { "expr": "sqlite_users_count" }
   ]
  },
  {
   "title": "Games Count",
   "type": "stat",
   "gridPos": { "x": 8, "y": 32, "w": 8, "h": 4 },
   "targets": [
    { "expr": "sqlite_games_count" }
   ]
  },
  {
   "title": "Tournaments Count",
   "type": "stat",
   "gridPos": { "x": 16, "y": 32, "w": 8, "h": 4 },
   "targets": [
    { "expr": "sqlite_tournaments_count" }
   ]
  }
 ]
}